whitelist:
  - path: /register
    methods: [POST]
  - path: /login
    methods: [POST]
  - path: /test_auth
    methods: [GET]
  - path: /public/*
    methods: [GET,POST]
  - path: /product/*
    methods: [GET,POST]
  - path: /cart/*
    methods: [GET,POST,DELETE]
  - path: /order/*
    methods: [GET,POST]
  - path: /payment/*
    methods: [POST]
  - path: /checkout/*
    methods: [POST]
  