whitelist:
  - path: /register
    methods: [POST]
  - path: /login
    methods: [POST]
  - path: /test_auth
    methods: [GET]
  - path: /public/*
    methods: [GET,POST]
  - path: /products/*
    methods: [GET,POST]
  