server:
  name: "gateway"
  port: 8080

etcd:
  endpoints:
    - "localhost:2379"
  dial_timeout: 5
services:
  user_service: "localhost:50051"
  auth_service: "localhost:50052"
  product_service: "localhost:50053"
